local function read(path)
    local file = assert(io.open(path, "rb"))
    local source = file:read("*a")
    file:close()
    return source
end

local function module(name, path)
    return "local " .. name .. " = (function()\n" .. read(path) .. "\nend)()\n"
end

for _, route in ipairs({ "lobby", "dungeon" }) do
    local parts = {
        "-- Generated by lua build.lua. Edit src/ files, then rebuild.\n",
        "if not game:IsLoaded() then game.Loaded:Wait() end\n",
        module("Logic", "src/HubLogic.luau"),
        module("Adapter", "src/GameAdapter.luau"),
    }
    if route == "dungeon" then
        table.insert(parts, "local function createController()\n" .. read("src/CombatController.luau") .. "\nend\n")
    end
    table.insert(parts, read(route == "lobby" and "src/Lobby.luau" or "src/Dungeon.luau"))
    table.insert(parts, "\n" .. read("src/ObsidianHub.luau"))
    local file = assert(io.open("dist/" .. route .. ".luau", "wb"))
    file:write(table.concat(parts))
    file:close()
    print("Built dist/" .. route .. ".luau")
end
